### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by StephenChow2713** [Dawish/GoogleArchitectureDemo#1]
studio导入之后，提示几乎所有的gradle中的依赖都报错，Unable to resolve dependency for ...Could not download ...jar or aar

**Comment by StephenChow2713** [comment]
对gradle的问题不是很懂，别见怪

**Comment by Dawish** [comment]
可能是跟你本地的gradle版本不匹配，把你本地的sdk和gradle都更新到最新版本，AS也需要3,.0+，项目有很多依赖，你需要耐心等待下载编译。

**Comment by StephenChow2713** [comment]
我Studio是3.0 gradle版本也是4.1 插件版本是3.0.0，可是就是提示会报错，
Error:Unable to resolve dependency for ':app_specific@debugUnitTest/compileClasspath': Could not download gson.jar (com.google.code.gson:gson:2.7)
<a href="openFile:C:/Workspace/GoogleArchitectureDemo/app_specific/build.gradle">Open File</a><br><a href="Unable to resolve dependency for &#39;:app_specific@debugUnitTest/compileClasspath&#39;: Could not download gson.jar (com.google.code.gson:gson:2.7)">Show Details</a>
不只是gson，还有okhttp等都是这样

**Comment by Dawish** [comment]
clean project后多编译几次

**Comment by StephenChow2713** [comment]
项目不报错，是gradle sync一直再报错，clean不起作用，提示无法解析那些依赖

**Comment by StephenChow2713** [comment]
你导入项目的时候，是整个工程直接导入的吧

**Comment by Dawish** [comment]
如果可以，请翻一下qiang

**Comment by StephenChow2713** [comment]
好了，谢谢你，这种问题也愿意解答

**Comment by sihaixuan** [comment]
这个是okhttp依赖冲突，
api('com.facebook.fresco:imagepipeline-okhttp3:0.12.0', {
        exclude module: "okhttp"
    })
这样可以解决。
