### ISSUE TITLE
个人一些想法

### ISSUE THREAD

**Issue by tanhuanpei** [Dawish/GoogleArchitectureDemo#8]
项目思路很好，但有个地方不是很认同，把业务逻辑都共用在lib_coremodel，这不符合模块化思想吧。例如news和girsl的接口请求已经耦合在同一个模块，如果项目来一个需求，需要girls单独成立一个app。lib_coremodel里面news的代码已经是多余的了。

**Comment by Dawish** [comment]
我当时只是想着提供一个思路，跟业务具体的思路，需开发进一步拆分了。
